// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgPgKaLaSrgSdML5N4naVO3R9v7jd6rBk',
    appId: '1:130075181497:android:59a85f14fece0fd5ca7668',
    messagingSenderId: '130075181497',
    projectId: 'streato-app',
    storageBucket: 'streato-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgNEldDTFmrZaSSzou4awnWh91XNQVhz4',
    appId: '1:130075181497:ios:77cfbb7d4ab7fd55ca7668',
    messagingSenderId: '130075181497',
    projectId: 'streato-app',
    storageBucket: 'streato-app.firebasestorage.app',
    iosClientId: '130075181497-bsp6vo5fbugrd4kscjftg38bflhu0fjs.apps.googleusercontent.com',
    iosBundleId: 'com.example.streatoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgNEldDTFmrZaSSzou4awnWh91XNQVhz4',
    appId: '1:130075181497:ios:77cfbb7d4ab7fd55ca7668',
    messagingSenderId: '130075181497',
    projectId: 'streato-app',
    storageBucket: 'streato-app.firebasestorage.app',
    iosClientId: '130075181497-bsp6vo5fbugrd4kscjftg38bflhu0fjs.apps.googleusercontent.com',
    iosBundleId: 'com.example.streatoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChVPDoY3E9aLRp5Dkq2P3H-O8wwAWqSfY',
    appId: '1:130075181497:web:cacb6e3fd87e1d0dca7668',
    messagingSenderId: '130075181497',
    projectId: 'streato-app',
    authDomain: 'streato-app.firebaseapp.com',
    storageBucket: 'streato-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChVPDoY3E9aLRp5Dkq2P3H-O8wwAWqSfY',
    appId: '1:130075181497:web:24aa96551dd7e186ca7668',
    messagingSenderId: '130075181497',
    projectId: 'streato-app',
    authDomain: 'streato-app.firebaseapp.com',
    storageBucket: 'streato-app.firebasestorage.app',
  );

}